export const countries = [
  {
    "id": 1,
    "name": "Afghanistan",
    "iso2": "AF",
    "iso3": "AFG",
    "phonecode": "93",
    "capital": "Kabul",
    "currency": "AFN",
    "native": "افغانستان",
    "emoji": "🇦🇫"
  },
  {
    "id": 2,
    "name": "Aland Islands",
    "iso2": "AX",
    "iso3": "ALA",
    "phonecode": "+358-18",
    "capital": "Mariehamn",
    "currency": "EUR",
    "native": "Åland",
    "emoji": "🇦🇽"
  },
  {
    "id": 3,
    "name": "Albania",
    "iso2": "AL",
    "iso3": "ALB",
    "phonecode": "355",
    "capital": "Tirana",
    "currency": "ALL",
    "native": "Shqipëria",
    "emoji": "🇦🇱"
  },
  {
    "id": 4,
    "name": "Algeria",
    "iso2": "DZ",
    "iso3": "DZA",
    "phonecode": "213",
    "capital": "Algiers",
    "currency": "DZD",
    "native": "الجزائر",
    "emoji": "🇩🇿"
  },
  {
    "id": 5,
    "name": "American Samoa",
    "iso2": "AS",
    "iso3": "ASM",
    "phonecode": "+1-684",
    "capital": "Pago Pago",
    "currency": "USD",
    "native": "American Samoa",
    "emoji": "🇦🇸"
  },
  {
    "id": 6,
    "name": "Andorra",
    "iso2": "AD",
    "iso3": "AND",
    "phonecode": "376",
    "capital": "Andorra la Vella",
    "currency": "EUR",
    "native": "Andorra",
    "emoji": "🇦🇩"
  },
  {
    "id": 7,
    "name": "Angola",
    "iso2": "AO",
    "iso3": "AGO",
    "phonecode": "244",
    "capital": "Luanda",
    "currency": "AOA",
    "native": "Angola",
    "emoji": "🇦🇴"
  },
  {
    "id": 8,
    "name": "Anguilla",
    "iso2": "AI",
    "iso3": "AIA",
    "phonecode": "+1-264",
    "capital": "The Valley",
    "currency": "XCD",
    "native": "Anguilla",
    "emoji": "🇦🇮"
  },
  {
    "id": 9,
    "name": "Antarctica",
    "iso2": "AQ",
    "iso3": "ATA",
    "phonecode": "672",
    "capital": "",
    "currency": "AAD",
    "native": "Antarctica",
    "emoji": "🇦🇶"
  },
  {
    "id": 10,
    "name": "Antigua And Barbuda",
    "iso2": "AG",
    "iso3": "ATG",
    "phonecode": "+1-268",
    "capital": "St. John's",
    "currency": "XCD",
    "native": "Antigua and Barbuda",
    "emoji": "🇦🇬"
  },
  {
    "id": 11,
    "name": "Argentina",
    "iso2": "AR",
    "iso3": "ARG",
    "phonecode": "54",
    "capital": "Buenos Aires",
    "currency": "ARS",
    "native": "Argentina",
    "emoji": "🇦🇷"
  },
  {
    "id": 12,
    "name": "Armenia",
    "iso2": "AM",
    "iso3": "ARM",
    "phonecode": "374",
    "capital": "Yerevan",
    "currency": "AMD",
    "native": "Հայաստան",
    "emoji": "🇦🇲"
  },
  {
    "id": 13,
    "name": "Aruba",
    "iso2": "AW",
    "iso3": "ABW",
    "phonecode": "297",
    "capital": "Oranjestad",
    "currency": "AWG",
    "native": "Aruba",
    "emoji": "🇦🇼"
  },
  {
    "id": 14,
    "name": "Australia",
    "iso2": "AU",
    "iso3": "AUS",
    "phonecode": "61",
    "capital": "Canberra",
    "currency": "AUD",
    "native": "Australia",
    "emoji": "🇦🇺"
  },
  {
    "id": 15,
    "name": "Austria",
    "iso2": "AT",
    "iso3": "AUT",
    "phonecode": "43",
    "capital": "Vienna",
    "currency": "EUR",
    "native": "Österreich",
    "emoji": "🇦🇹"
  },
  {
    "id": 16,
    "name": "Azerbaijan",
    "iso2": "AZ",
    "iso3": "AZE",
    "phonecode": "994",
    "capital": "Baku",
    "currency": "AZN",
    "native": "Azərbaycan",
    "emoji": "🇦🇿"
  },
  {
    "id": 17,
    "name": "The Bahamas",
    "iso2": "BS",
    "iso3": "BHS",
    "phonecode": "+1-242",
    "capital": "Nassau",
    "currency": "BSD",
    "native": "Bahamas",
    "emoji": "🇧🇸"
  },
  {
    "id": 18,
    "name": "Bahrain",
    "iso2": "BH",
    "iso3": "BHR",
    "phonecode": "973",
    "capital": "Manama",
    "currency": "BHD",
    "native": "‏البحرين",
    "emoji": "🇧🇭"
  },
  {
    "id": 19,
    "name": "Bangladesh",
    "iso2": "BD",
    "iso3": "BGD",
    "phonecode": "880",
    "capital": "Dhaka",
    "currency": "BDT",
    "native": "Bangladesh",
    "emoji": "🇧🇩"
  },
  {
    "id": 20,
    "name": "Barbados",
    "iso2": "BB",
    "iso3": "BRB",
    "phonecode": "+1-246",
    "capital": "Bridgetown",
    "currency": "BBD",
    "native": "Barbados",
    "emoji": "🇧🇧"
  },
  {
    "id": 21,
    "name": "Belarus",
    "iso2": "BY",
    "iso3": "BLR",
    "phonecode": "375",
    "capital": "Minsk",
    "currency": "BYN",
    "native": "Белару́сь",
    "emoji": "🇧🇾"
  },
  {
    "id": 22,
    "name": "Belgium",
    "iso2": "BE",
    "iso3": "BEL",
    "phonecode": "32",
    "capital": "Brussels",
    "currency": "EUR",
    "native": "België",
    "emoji": "🇧🇪"
  },
  {
    "id": 23,
    "name": "Belize",
    "iso2": "BZ",
    "iso3": "BLZ",
    "phonecode": "501",
    "capital": "Belmopan",
    "currency": "BZD",
    "native": "Belize",
    "emoji": "🇧🇿"
  },
  {
    "id": 24,
    "name": "Benin",
    "iso2": "BJ",
    "iso3": "BEN",
    "phonecode": "229",
    "capital": "Porto-Novo",
    "currency": "XOF",
    "native": "Bénin",
    "emoji": "🇧🇯"
  },
  {
    "id": 25,
    "name": "Bermuda",
    "iso2": "BM",
    "iso3": "BMU",
    "phonecode": "+1-441",
    "capital": "Hamilton",
    "currency": "BMD",
    "native": "Bermuda",
    "emoji": "🇧🇲"
  },
  {
    "id": 26,
    "name": "Bhutan",
    "iso2": "BT",
    "iso3": "BTN",
    "phonecode": "975",
    "capital": "Thimphu",
    "currency": "BTN",
    "native": "ʼbrug-yul",
    "emoji": "🇧🇹"
  },
  {
    "id": 27,
    "name": "Bolivia",
    "iso2": "BO",
    "iso3": "BOL",
    "phonecode": "591",
    "capital": "Sucre",
    "currency": "BOB",
    "native": "Bolivia",
    "emoji": "🇧🇴"
  },
  {
    "id": 28,
    "name": "Bosnia and Herzegovina",
    "iso2": "BA",
    "iso3": "BIH",
    "phonecode": "387",
    "capital": "Sarajevo",
    "currency": "BAM",
    "native": "Bosna i Hercegovina",
    "emoji": "🇧🇦"
  },
  {
    "id": 29,
    "name": "Botswana",
    "iso2": "BW",
    "iso3": "BWA",
    "phonecode": "267",
    "capital": "Gaborone",
    "currency": "BWP",
    "native": "Botswana",
    "emoji": "🇧🇼"
  },
  {
    "id": 30,
    "name": "Bouvet Island",
    "iso2": "BV",
    "iso3": "BVT",
    "phonecode": "0055",
    "capital": "",
    "currency": "NOK",
    "native": "Bouvetøya",
    "emoji": "🇧🇻"
  },
  {
    "id": 31,
    "name": "Brazil",
    "iso2": "BR",
    "iso3": "BRA",
    "phonecode": "55",
    "capital": "Brasilia",
    "currency": "BRL",
    "native": "Brasil",
    "emoji": "🇧🇷"
  },
  {
    "id": 32,
    "name": "British Indian Ocean Territory",
    "iso2": "IO",
    "iso3": "IOT",
    "phonecode": "246",
    "capital": "Diego Garcia",
    "currency": "USD",
    "native": "British Indian Ocean Territory",
    "emoji": "🇮🇴"
  },
  {
    "id": 33,
    "name": "Brunei",
    "iso2": "BN",
    "iso3": "BRN",
    "phonecode": "673",
    "capital": "Bandar Seri Begawan",
    "currency": "BND",
    "native": "Negara Brunei Darussalam",
    "emoji": "🇧🇳"
  },
  {
    "id": 34,
    "name": "Bulgaria",
    "iso2": "BG",
    "iso3": "BGR",
    "phonecode": "359",
    "capital": "Sofia",
    "currency": "BGN",
    "native": "България",
    "emoji": "🇧🇬"
  },
  {
    "id": 35,
    "name": "Burkina Faso",
    "iso2": "BF",
    "iso3": "BFA",
    "phonecode": "226",
    "capital": "Ouagadougou",
    "currency": "XOF",
    "native": "Burkina Faso",
    "emoji": "🇧🇫"
  },
  {
    "id": 36,
    "name": "Burundi",
    "iso2": "BI",
    "iso3": "BDI",
    "phonecode": "257",
    "capital": "Bujumbura",
    "currency": "BIF",
    "native": "Burundi",
    "emoji": "🇧🇮"
  },
  {
    "id": 37,
    "name": "Cambodia",
    "iso2": "KH",
    "iso3": "KHM",
    "phonecode": "855",
    "capital": "Phnom Penh",
    "currency": "KHR",
    "native": "Kâmpŭchéa",
    "emoji": "🇰🇭"
  },
  {
    "id": 38,
    "name": "Cameroon",
    "iso2": "CM",
    "iso3": "CMR",
    "phonecode": "237",
    "capital": "Yaounde",
    "currency": "XAF",
    "native": "Cameroon",
    "emoji": "🇨🇲"
  },
  {
    "id": 39,
    "name": "Canada",
    "iso2": "CA",
    "iso3": "CAN",
    "phonecode": "1",
    "capital": "Ottawa",
    "currency": "CAD",
    "native": "Canada",
    "emoji": "🇨🇦"
  },
  {
    "id": 40,
    "name": "Cape Verde",
    "iso2": "CV",
    "iso3": "CPV",
    "phonecode": "238",
    "capital": "Praia",
    "currency": "CVE",
    "native": "Cabo Verde",
    "emoji": "🇨🇻"
  },
  {
    "id": 41,
    "name": "Cayman Islands",
    "iso2": "KY",
    "iso3": "CYM",
    "phonecode": "+1-345",
    "capital": "George Town",
    "currency": "KYD",
    "native": "Cayman Islands",
    "emoji": "🇰🇾"
  },
  {
    "id": 42,
    "name": "Central African Republic",
    "iso2": "CF",
    "iso3": "CAF",
    "phonecode": "236",
    "capital": "Bangui",
    "currency": "XAF",
    "native": "Ködörösêse tî Bêafrîka",
    "emoji": "🇨🇫"
  },
  {
    "id": 43,
    "name": "Chad",
    "iso2": "TD",
    "iso3": "TCD",
    "phonecode": "235",
    "capital": "N'Djamena",
    "currency": "XAF",
    "native": "Tchad",
    "emoji": "🇹🇩"
  },
  {
    "id": 44,
    "name": "Chile",
    "iso2": "CL",
    "iso3": "CHL",
    "phonecode": "56",
    "capital": "Santiago",
    "currency": "CLP",
    "native": "Chile",
    "emoji": "🇨🇱"
  },
  {
    "id": 45,
    "name": "China",
    "iso2": "CN",
    "iso3": "CHN",
    "phonecode": "86",
    "capital": "Beijing",
    "currency": "CNY",
    "native": "中国",
    "emoji": "🇨🇳"
  },
  {
    "id": 46,
    "name": "Christmas Island",
    "iso2": "CX",
    "iso3": "CXR",
    "phonecode": "61",
    "capital": "Flying Fish Cove",
    "currency": "AUD",
    "native": "Christmas Island",
    "emoji": "🇨🇽"
  },
  {
    "id": 47,
    "name": "Cocos (Keeling) Islands",
    "iso2": "CC",
    "iso3": "CCK",
    "phonecode": "61",
    "capital": "West Island",
    "currency": "AUD",
    "native": "Cocos (Keeling) Islands",
    "emoji": "🇨🇨"
  },
  {
    "id": 48,
    "name": "Colombia",
    "iso2": "CO",
    "iso3": "COL",
    "phonecode": "57",
    "capital": "Bogotá",
    "currency": "COP",
    "native": "Colombia",
    "emoji": "🇨🇴"
  },
  {
    "id": 49,
    "name": "Comoros",
    "iso2": "KM",
    "iso3": "COM",
    "phonecode": "269",
    "capital": "Moroni",
    "currency": "KMF",
    "native": "Komori",
    "emoji": "🇰🇲"
  },
  {
    "id": 50,
    "name": "Congo",
    "iso2": "CG",
    "iso3": "COG",
    "phonecode": "242",
    "capital": "Brazzaville",
    "currency": "XAF",
    "native": "République du Congo",
    "emoji": "🇨🇬"
  },
  {
    "id": 51,
    "name": "Democratic Republic of the Congo",
    "iso2": "CD",
    "iso3": "COD",
    "phonecode": "243",
    "capital": "Kinshasa",
    "currency": "CDF",
    "native": "République démocratique du Congo",
    "emoji": "🇨🇩"
  },
  {
    "id": 52,
    "name": "Cook Islands",
    "iso2": "CK",
    "iso3": "COK",
    "phonecode": "682",
    "capital": "Avarua",
    "currency": "NZD",
    "native": "Cook Islands",
    "emoji": "🇨🇰"
  },
  {
    "id": 53,
    "name": "Costa Rica",
    "iso2": "CR",
    "iso3": "CRI",
    "phonecode": "506",
    "capital": "San Jose",
    "currency": "CRC",
    "native": "Costa Rica",
    "emoji": "🇨🇷"
  },
  {
    "id": 54,
    "name": "Cote D'Ivoire (Ivory Coast)",
    "iso2": "CI",
    "iso3": "CIV",
    "phonecode": "225",
    "capital": "Yamoussoukro",
    "currency": "XOF",
    "native": null,
    "emoji": "🇨🇮"
  },
  {
    "id": 55,
    "name": "Croatia",
    "iso2": "HR",
    "iso3": "HRV",
    "phonecode": "385",
    "capital": "Zagreb",
    "currency": "HRK",
    "native": "Hrvatska",
    "emoji": "🇭🇷"
  },
  {
    "id": 56,
    "name": "Cuba",
    "iso2": "CU",
    "iso3": "CUB",
    "phonecode": "53",
    "capital": "Havana",
    "currency": "CUP",
    "native": "Cuba",
    "emoji": "🇨🇺"
  },
  {
    "id": 57,
    "name": "Cyprus",
    "iso2": "CY",
    "iso3": "CYP",
    "phonecode": "357",
    "capital": "Nicosia",
    "currency": "EUR",
    "native": "Κύπρος",
    "emoji": "🇨🇾"
  },
  {
    "id": 58,
    "name": "Czech Republic",
    "iso2": "CZ",
    "iso3": "CZE",
    "phonecode": "420",
    "capital": "Prague",
    "currency": "CZK",
    "native": "Česká republika",
    "emoji": "🇨🇿"
  },
  {
    "id": 59,
    "name": "Denmark",
    "iso2": "DK",
    "iso3": "DNK",
    "phonecode": "45",
    "capital": "Copenhagen",
    "currency": "DKK",
    "native": "Danmark",
    "emoji": "🇩🇰"
  },
  {
    "id": 60,
    "name": "Djibouti",
    "iso2": "DJ",
    "iso3": "DJI",
    "phonecode": "253",
    "capital": "Djibouti",
    "currency": "DJF",
    "native": "Djibouti",
    "emoji": "🇩🇯"
  },
  {
    "id": 61,
    "name": "Dominica",
    "iso2": "DM",
    "iso3": "DMA",
    "phonecode": "+1-767",
    "capital": "Roseau",
    "currency": "XCD",
    "native": "Dominica",
    "emoji": "🇩🇲"
  },
  {
    "id": 62,
    "name": "Dominican Republic",
    "iso2": "DO",
    "iso3": "DOM",
    "phonecode": "+1-809 and 1-829",
    "capital": "Santo Domingo",
    "currency": "DOP",
    "native": "República Dominicana",
    "emoji": "🇩🇴"
  },
  {
    "id": 63,
    "name": "East Timor",
    "iso2": "TL",
    "iso3": "TLS",
    "phonecode": "670",
    "capital": "Dili",
    "currency": "USD",
    "native": "Timor-Leste",
    "emoji": "🇹🇱"
  },
  {
    "id": 64,
    "name": "Ecuador",
    "iso2": "EC",
    "iso3": "ECU",
    "phonecode": "593",
    "capital": "Quito",
    "currency": "USD",
    "native": "Ecuador",
    "emoji": "🇪🇨"
  },
  {
    "id": 65,
    "name": "Egypt",
    "iso2": "EG",
    "iso3": "EGY",
    "phonecode": "20",
    "capital": "Cairo",
    "currency": "EGP",
    "native": "مصر‎",
    "emoji": "🇪🇬"
  },
  {
    "id": 66,
    "name": "El Salvador",
    "iso2": "SV",
    "iso3": "SLV",
    "phonecode": "503",
    "capital": "San Salvador",
    "currency": "USD",
    "native": "El Salvador",
    "emoji": "🇸🇻"
  },
  {
    "id": 67,
    "name": "Equatorial Guinea",
    "iso2": "GQ",
    "iso3": "GNQ",
    "phonecode": "240",
    "capital": "Malabo",
    "currency": "XAF",
    "native": "Guinea Ecuatorial",
    "emoji": "🇬🇶"
  },
  {
    "id": 68,
    "name": "Eritrea",
    "iso2": "ER",
    "iso3": "ERI",
    "phonecode": "291",
    "capital": "Asmara",
    "currency": "ERN",
    "native": "ኤርትራ",
    "emoji": "🇪🇷"
  },
  {
    "id": 69,
    "name": "Estonia",
    "iso2": "EE",
    "iso3": "EST",
    "phonecode": "372",
    "capital": "Tallinn",
    "currency": "EUR",
    "native": "Eesti",
    "emoji": "🇪🇪"
  },
  {
    "id": 70,
    "name": "Ethiopia",
    "iso2": "ET",
    "iso3": "ETH",
    "phonecode": "251",
    "capital": "Addis Ababa",
    "currency": "ETB",
    "native": "ኢትዮጵያ",
    "emoji": "🇪🇹"
  },
  {
    "id": 71,
    "name": "Falkland Islands",
    "iso2": "FK",
    "iso3": "FLK",
    "phonecode": "500",
    "capital": "Stanley",
    "currency": "FKP",
    "native": "Falkland Islands",
    "emoji": "🇫🇰"
  },
  {
    "id": 72,
    "name": "Faroe Islands",
    "iso2": "FO",
    "iso3": "FRO",
    "phonecode": "298",
    "capital": "Torshavn",
    "currency": "DKK",
    "native": "Føroyar",
    "emoji": "🇫🇴"
  },
  {
    "id": 73,
    "name": "Fiji Islands",
    "iso2": "FJ",
    "iso3": "FJI",
    "phonecode": "679",
    "capital": "Suva",
    "currency": "FJD",
    "native": "Fiji",
    "emoji": "🇫🇯"
  },
  {
    "id": 74,
    "name": "Finland",
    "iso2": "FI",
    "iso3": "FIN",
    "phonecode": "358",
    "capital": "Helsinki",
    "currency": "EUR",
    "native": "Suomi",
    "emoji": "🇫🇮"
  },
  {
    "id": 75,
    "name": "France",
    "iso2": "FR",
    "iso3": "FRA",
    "phonecode": "33",
    "capital": "Paris",
    "currency": "EUR",
    "native": "France",
    "emoji": "🇫🇷"
  },
  {
    "id": 76,
    "name": "French Guiana",
    "iso2": "GF",
    "iso3": "GUF",
    "phonecode": "594",
    "capital": "Cayenne",
    "currency": "EUR",
    "native": "Guyane française",
    "emoji": "🇬🇫"
  },
  {
    "id": 77,
    "name": "French Polynesia",
    "iso2": "PF",
    "iso3": "PYF",
    "phonecode": "689",
    "capital": "Papeete",
    "currency": "XPF",
    "native": "Polynésie française",
    "emoji": "🇵🇫"
  },
  {
    "id": 78,
    "name": "French Southern Territories",
    "iso2": "TF",
    "iso3": "ATF",
    "phonecode": "262",
    "capital": "Port-aux-Francais",
    "currency": "EUR",
    "native": "Territoire des Terres australes et antarctiques fr",
    "emoji": "🇹🇫"
  },
  {
    "id": 79,
    "name": "Gabon",
    "iso2": "GA",
    "iso3": "GAB",
    "phonecode": "241",
    "capital": "Libreville",
    "currency": "XAF",
    "native": "Gabon",
    "emoji": "🇬🇦"
  },
  {
    "id": 80,
    "name": "Gambia The",
    "iso2": "GM",
    "iso3": "GMB",
    "phonecode": "220",
    "capital": "Banjul",
    "currency": "GMD",
    "native": "Gambia",
    "emoji": "🇬🇲"
  },
  {
    "id": 81,
    "name": "Georgia",
    "iso2": "GE",
    "iso3": "GEO",
    "phonecode": "995",
    "capital": "Tbilisi",
    "currency": "GEL",
    "native": "საქართველო",
    "emoji": "🇬🇪"
  },
  {
    "id": 82,
    "name": "Germany",
    "iso2": "DE",
    "iso3": "DEU",
    "phonecode": "49",
    "capital": "Berlin",
    "currency": "EUR",
    "native": "Deutschland",
    "emoji": "🇩🇪"
  },
  {
    "id": 83,
    "name": "Ghana",
    "iso2": "GH",
    "iso3": "GHA",
    "phonecode": "233",
    "capital": "Accra",
    "currency": "GHS",
    "native": "Ghana",
    "emoji": "🇬🇭"
  },
  {
    "id": 84,
    "name": "Gibraltar",
    "iso2": "GI",
    "iso3": "GIB",
    "phonecode": "350",
    "capital": "Gibraltar",
    "currency": "GIP",
    "native": "Gibraltar",
    "emoji": "🇬🇮"
  },
  {
    "id": 85,
    "name": "Greece",
    "iso2": "GR",
    "iso3": "GRC",
    "phonecode": "30",
    "capital": "Athens",
    "currency": "EUR",
    "native": "Ελλάδα",
    "emoji": "🇬🇷"
  },
  {
    "id": 86,
    "name": "Greenland",
    "iso2": "GL",
    "iso3": "GRL",
    "phonecode": "299",
    "capital": "Nuuk",
    "currency": "DKK",
    "native": "Kalaallit Nunaat",
    "emoji": "🇬🇱"
  },
  {
    "id": 87,
    "name": "Grenada",
    "iso2": "GD",
    "iso3": "GRD",
    "phonecode": "+1-473",
    "capital": "St. George's",
    "currency": "XCD",
    "native": "Grenada",
    "emoji": "🇬🇩"
  },
  {
    "id": 88,
    "name": "Guadeloupe",
    "iso2": "GP",
    "iso3": "GLP",
    "phonecode": "590",
    "capital": "Basse-Terre",
    "currency": "EUR",
    "native": "Guadeloupe",
    "emoji": "🇬🇵"
  },
  {
    "id": 89,
    "name": "Guam",
    "iso2": "GU",
    "iso3": "GUM",
    "phonecode": "+1-671",
    "capital": "Hagatna",
    "currency": "USD",
    "native": "Guam",
    "emoji": "🇬🇺"
  },
  {
    "id": 90,
    "name": "Guatemala",
    "iso2": "GT",
    "iso3": "GTM",
    "phonecode": "502",
    "capital": "Guatemala City",
    "currency": "GTQ",
    "native": "Guatemala",
    "emoji": "🇬🇹"
  },
  {
    "id": 91,
    "name": "Guernsey and Alderney",
    "iso2": "GG",
    "iso3": "GGY",
    "phonecode": "+44-1481",
    "capital": "St Peter Port",
    "currency": "GBP",
    "native": "Guernsey",
    "emoji": "🇬🇬"
  },
  {
    "id": 92,
    "name": "Guinea",
    "iso2": "GN",
    "iso3": "GIN",
    "phonecode": "224",
    "capital": "Conakry",
    "currency": "GNF",
    "native": "Guinée",
    "emoji": "🇬🇳"
  },
  {
    "id": 93,
    "name": "Guinea-Bissau",
    "iso2": "GW",
    "iso3": "GNB",
    "phonecode": "245",
    "capital": "Bissau",
    "currency": "XOF",
    "native": "Guiné-Bissau",
    "emoji": "🇬🇼"
  },
  {
    "id": 94,
    "name": "Guyana",
    "iso2": "GY",
    "iso3": "GUY",
    "phonecode": "592",
    "capital": "Georgetown",
    "currency": "GYD",
    "native": "Guyana",
    "emoji": "🇬🇾"
  },
  {
    "id": 95,
    "name": "Haiti",
    "iso2": "HT",
    "iso3": "HTI",
    "phonecode": "509",
    "capital": "Port-au-Prince",
    "currency": "HTG",
    "native": "Haïti",
    "emoji": "🇭🇹"
  },
  {
    "id": 96,
    "name": "Heard Island and McDonald Islands",
    "iso2": "HM",
    "iso3": "HMD",
    "phonecode": "672",
    "capital": "",
    "currency": "AUD",
    "native": "Heard Island and McDonald Islands",
    "emoji": "🇭🇲"
  },
  {
    "id": 97,
    "name": "Honduras",
    "iso2": "HN",
    "iso3": "HND",
    "phonecode": "504",
    "capital": "Tegucigalpa",
    "currency": "HNL",
    "native": "Honduras",
    "emoji": "🇭🇳"
  },
  {
    "id": 98,
    "name": "Hong Kong S.A.R.",
    "iso2": "HK",
    "iso3": "HKG",
    "phonecode": "852",
    "capital": "Hong Kong",
    "currency": "HKD",
    "native": "香港",
    "emoji": "🇭🇰"
  },
  {
    "id": 99,
    "name": "Hungary",
    "iso2": "HU",
    "iso3": "HUN",
    "phonecode": "36",
    "capital": "Budapest",
    "currency": "HUF",
    "native": "Magyarország",
    "emoji": "🇭🇺"
  },
  {
    "id": 100,
    "name": "Iceland",
    "iso2": "IS",
    "iso3": "ISL",
    "phonecode": "354",
    "capital": "Reykjavik",
    "currency": "ISK",
    "native": "Ísland",
    "emoji": "🇮🇸"
  },
  {
    "id": 101,
    "name": "India",
    "iso2": "IN",
    "iso3": "IND",
    "phonecode": "91",
    "capital": "New Delhi",
    "currency": "INR",
    "native": "भारत",
    "emoji": "🇮🇳"
  },
  {
    "id": 102,
    "name": "Indonesia",
    "iso2": "ID",
    "iso3": "IDN",
    "phonecode": "62",
    "capital": "Jakarta",
    "currency": "IDR",
    "native": "Indonesia",
    "emoji": "🇮🇩"
  },
  {
    "id": 103,
    "name": "Iran",
    "iso2": "IR",
    "iso3": "IRN",
    "phonecode": "98",
    "capital": "Tehran",
    "currency": "IRR",
    "native": "ایران",
    "emoji": "🇮🇷"
  },
  {
    "id": 104,
    "name": "Iraq",
    "iso2": "IQ",
    "iso3": "IRQ",
    "phonecode": "964",
    "capital": "Baghdad",
    "currency": "IQD",
    "native": "العراق",
    "emoji": "🇮🇶"
  },
  {
    "id": 105,
    "name": "Ireland",
    "iso2": "IE",
    "iso3": "IRL",
    "phonecode": "353",
    "capital": "Dublin",
    "currency": "EUR",
    "native": "Éire",
    "emoji": "🇮🇪"
  },
  {
    "id": 106,
    "name": "Israel",
    "iso2": "IL",
    "iso3": "ISR",
    "phonecode": "972",
    "capital": "Jerusalem",
    "currency": "ILS",
    "native": "יִשְׂרָאֵל",
    "emoji": "🇮🇱"
  },
  {
    "id": 107,
    "name": "Italy",
    "iso2": "IT",
    "iso3": "ITA",
    "phonecode": "39",
    "capital": "Rome",
    "currency": "EUR",
    "native": "Italia",
    "emoji": "🇮🇹"
  },
  {
    "id": 108,
    "name": "Jamaica",
    "iso2": "JM",
    "iso3": "JAM",
    "phonecode": "+1-876",
    "capital": "Kingston",
    "currency": "JMD",
    "native": "Jamaica",
    "emoji": "🇯🇲"
  },
  {
    "id": 109,
    "name": "Japan",
    "iso2": "JP",
    "iso3": "JPN",
    "phonecode": "81",
    "capital": "Tokyo",
    "currency": "JPY",
    "native": "日本",
    "emoji": "🇯🇵"
  },
  {
    "id": 110,
    "name": "Jersey",
    "iso2": "JE",
    "iso3": "JEY",
    "phonecode": "+44-1534",
    "capital": "Saint Helier",
    "currency": "GBP",
    "native": "Jersey",
    "emoji": "🇯🇪"
  },
  {
    "id": 111,
    "name": "Jordan",
    "iso2": "JO",
    "iso3": "JOR",
    "phonecode": "962",
    "capital": "Amman",
    "currency": "JOD",
    "native": "الأردن",
    "emoji": "🇯🇴"
  },
  {
    "id": 112,
    "name": "Kazakhstan",
    "iso2": "KZ",
    "iso3": "KAZ",
    "phonecode": "7",
    "capital": "Astana",
    "currency": "KZT",
    "native": "Қазақстан",
    "emoji": "🇰🇿"
  },
  {
    "id": 113,
    "name": "Kenya",
    "iso2": "KE",
    "iso3": "KEN",
    "phonecode": "254",
    "capital": "Nairobi",
    "currency": "KES",
    "native": "Kenya",
    "emoji": "🇰🇪"
  },
  {
    "id": 114,
    "name": "Kiribati",
    "iso2": "KI",
    "iso3": "KIR",
    "phonecode": "686",
    "capital": "Tarawa",
    "currency": "AUD",
    "native": "Kiribati",
    "emoji": "🇰🇮"
  },
  {
    "id": 115,
    "name": "North Korea",
    "iso2": "KP",
    "iso3": "PRK",
    "phonecode": "850",
    "capital": "Pyongyang",
    "currency": "KPW",
    "native": "북한",
    "emoji": "🇰🇵"
  },
  {
    "id": 116,
    "name": "South Korea",
    "iso2": "KR",
    "iso3": "KOR",
    "phonecode": "82",
    "capital": "Seoul",
    "currency": "KRW",
    "native": "대한민국",
    "emoji": "🇰🇷"
  },
  {
    "id": 117,
    "name": "Kuwait",
    "iso2": "KW",
    "iso3": "KWT",
    "phonecode": "965",
    "capital": "Kuwait City",
    "currency": "KWD",
    "native": "الكويت",
    "emoji": "🇰🇼"
  },
  {
    "id": 118,
    "name": "Kyrgyzstan",
    "iso2": "KG",
    "iso3": "KGZ",
    "phonecode": "996",
    "capital": "Bishkek",
    "currency": "KGS",
    "native": "Кыргызстан",
    "emoji": "🇰🇬"
  },
  {
    "id": 119,
    "name": "Laos",
    "iso2": "LA",
    "iso3": "LAO",
    "phonecode": "856",
    "capital": "Vientiane",
    "currency": "LAK",
    "native": "ສປປລາວ",
    "emoji": "🇱🇦"
  },
  {
    "id": 120,
    "name": "Latvia",
    "iso2": "LV",
    "iso3": "LVA",
    "phonecode": "371",
    "capital": "Riga",
    "currency": "EUR",
    "native": "Latvija",
    "emoji": "🇱🇻"
  },
  {
    "id": 121,
    "name": "Lebanon",
    "iso2": "LB",
    "iso3": "LBN",
    "phonecode": "961",
    "capital": "Beirut",
    "currency": "LBP",
    "native": "لبنان",
    "emoji": "🇱🇧"
  },
  {
    "id": 122,
    "name": "Lesotho",
    "iso2": "LS",
    "iso3": "LSO",
    "phonecode": "266",
    "capital": "Maseru",
    "currency": "LSL",
    "native": "Lesotho",
    "emoji": "🇱🇸"
  },
  {
    "id": 123,
    "name": "Liberia",
    "iso2": "LR",
    "iso3": "LBR",
    "phonecode": "231",
    "capital": "Monrovia",
    "currency": "LRD",
    "native": "Liberia",
    "emoji": "🇱🇷"
  },
  {
    "id": 124,
    "name": "Libya",
    "iso2": "LY",
    "iso3": "LBY",
    "phonecode": "218",
    "capital": "Tripolis",
    "currency": "LYD",
    "native": "‏ليبيا",
    "emoji": "🇱🇾"
  },
  {
    "id": 125,
    "name": "Liechtenstein",
    "iso2": "LI",
    "iso3": "LIE",
    "phonecode": "423",
    "capital": "Vaduz",
    "currency": "CHF",
    "native": "Liechtenstein",
    "emoji": "🇱🇮"
  },
  {
    "id": 126,
    "name": "Lithuania",
    "iso2": "LT",
    "iso3": "LTU",
    "phonecode": "370",
    "capital": "Vilnius",
    "currency": "EUR",
    "native": "Lietuva",
    "emoji": "🇱🇹"
  },
  {
    "id": 127,
    "name": "Luxembourg",
    "iso2": "LU",
    "iso3": "LUX",
    "phonecode": "352",
    "capital": "Luxembourg",
    "currency": "EUR",
    "native": "Luxembourg",
    "emoji": "🇱🇺"
  },
  {
    "id": 128,
    "name": "Macau S.A.R.",
    "iso2": "MO",
    "iso3": "MAC",
    "phonecode": "853",
    "capital": "Macao",
    "currency": "MOP",
    "native": "澳門",
    "emoji": "🇲🇴"
  },
  {
    "id": 129,
    "name": "North Macedonia",
    "iso2": "MK",
    "iso3": "MKD",
    "phonecode": "389",
    "capital": "Skopje",
    "currency": "MKD",
    "native": "Северна Македонија",
    "emoji": "🇲🇰"
  },
  {
    "id": 130,
    "name": "Madagascar",
    "iso2": "MG",
    "iso3": "MDG",
    "phonecode": "261",
    "capital": "Antananarivo",
    "currency": "MGA",
    "native": "Madagasikara",
    "emoji": "🇲🇬"
  },
  {
    "id": 131,
    "name": "Malawi",
    "iso2": "MW",
    "iso3": "MWI",
    "phonecode": "265",
    "capital": "Lilongwe",
    "currency": "MWK",
    "native": "Malawi",
    "emoji": "🇲🇼"
  },
  {
    "id": 132,
    "name": "Malaysia",
    "iso2": "MY",
    "iso3": "MYS",
    "phonecode": "60",
    "capital": "Kuala Lumpur",
    "currency": "MYR",
    "native": "Malaysia",
    "emoji": "🇲🇾"
  },
  {
    "id": 133,
    "name": "Maldives",
    "iso2": "MV",
    "iso3": "MDV",
    "phonecode": "960",
    "capital": "Male",
    "currency": "MVR",
    "native": "Maldives",
    "emoji": "🇲🇻"
  },
  {
    "id": 134,
    "name": "Mali",
    "iso2": "ML",
    "iso3": "MLI",
    "phonecode": "223",
    "capital": "Bamako",
    "currency": "XOF",
    "native": "Mali",
    "emoji": "🇲🇱"
  },
  {
    "id": 135,
    "name": "Malta",
    "iso2": "MT",
    "iso3": "MLT",
    "phonecode": "356",
    "capital": "Valletta",
    "currency": "EUR",
    "native": "Malta",
    "emoji": "🇲🇹"
  },
  {
    "id": 136,
    "name": "Man (Isle of)",
    "iso2": "IM",
    "iso3": "IMN",
    "phonecode": "+44-1624",
    "capital": "Douglas, Isle of Man",
    "currency": "GBP",
    "native": "Isle of Man",
    "emoji": "🇮🇲"
  },
  {
    "id": 137,
    "name": "Marshall Islands",
    "iso2": "MH",
    "iso3": "MHL",
    "phonecode": "692",
    "capital": "Majuro",
    "currency": "USD",
    "native": "M̧ajeļ",
    "emoji": "🇲🇭"
  },
  {
    "id": 138,
    "name": "Martinique",
    "iso2": "MQ",
    "iso3": "MTQ",
    "phonecode": "596",
    "capital": "Fort-de-France",
    "currency": "EUR",
    "native": "Martinique",
    "emoji": "🇲🇶"
  },
  {
    "id": 139,
    "name": "Mauritania",
    "iso2": "MR",
    "iso3": "MRT",
    "phonecode": "222",
    "capital": "Nouakchott",
    "currency": "MRO",
    "native": "موريتانيا",
    "emoji": "🇲🇷"
  },
  {
    "id": 140,
    "name": "Mauritius",
    "iso2": "MU",
    "iso3": "MUS",
    "phonecode": "230",
    "capital": "Port Louis",
    "currency": "MUR",
    "native": "Maurice",
    "emoji": "🇲🇺"
  },
  {
    "id": 141,
    "name": "Mayotte",
    "iso2": "YT",
    "iso3": "MYT",
    "phonecode": "262",
    "capital": "Mamoudzou",
    "currency": "EUR",
    "native": "Mayotte",
    "emoji": "🇾🇹"
  },
  {
    "id": 142,
    "name": "Mexico",
    "iso2": "MX",
    "iso3": "MEX",
    "phonecode": "52",
    "capital": "Ciudad de México",
    "currency": "MXN",
    "native": "México",
    "emoji": "🇲🇽"
  },
  {
    "id": 143,
    "name": "Micronesia",
    "iso2": "FM",
    "iso3": "FSM",
    "phonecode": "691",
    "capital": "Palikir",
    "currency": "USD",
    "native": "Micronesia",
    "emoji": "🇫🇲"
  },
  {
    "id": 144,
    "name": "Moldova",
    "iso2": "MD",
    "iso3": "MDA",
    "phonecode": "373",
    "capital": "Chisinau",
    "currency": "MDL",
    "native": "Moldova",
    "emoji": "🇲🇩"
  },
  {
    "id": 145,
    "name": "Monaco",
    "iso2": "MC",
    "iso3": "MCO",
    "phonecode": "377",
    "capital": "Monaco",
    "currency": "EUR",
    "native": "Monaco",
    "emoji": "🇲🇨"
  },
  {
    "id": 146,
    "name": "Mongolia",
    "iso2": "MN",
    "iso3": "MNG",
    "phonecode": "976",
    "capital": "Ulan Bator",
    "currency": "MNT",
    "native": "Монгол улс",
    "emoji": "🇲🇳"
  },
  {
    "id": 147,
    "name": "Montenegro",
    "iso2": "ME",
    "iso3": "MNE",
    "phonecode": "382",
    "capital": "Podgorica",
    "currency": "EUR",
    "native": "Црна Гора",
    "emoji": "🇲🇪"
  },
  {
    "id": 148,
    "name": "Montserrat",
    "iso2": "MS",
    "iso3": "MSR",
    "phonecode": "+1-664",
    "capital": "Plymouth",
    "currency": "XCD",
    "native": "Montserrat",
    "emoji": "🇲🇸"
  },
  {
    "id": 149,
    "name": "Morocco",
    "iso2": "MA",
    "iso3": "MAR",
    "phonecode": "212",
    "capital": "Rabat",
    "currency": "MAD",
    "native": "المغرب",
    "emoji": "🇲🇦"
  },
  {
    "id": 150,
    "name": "Mozambique",
    "iso2": "MZ",
    "iso3": "MOZ",
    "phonecode": "258",
    "capital": "Maputo",
    "currency": "MZN",
    "native": "Moçambique",
    "emoji": "🇲🇿"
  },
  {
    "id": 151,
    "name": "Myanmar",
    "iso2": "MM",
    "iso3": "MMR",
    "phonecode": "95",
    "capital": "Nay Pyi Taw",
    "currency": "MMK",
    "native": "မြန်မာ",
    "emoji": "🇲🇲"
  },
  {
    "id": 152,
    "name": "Namibia",
    "iso2": "NA",
    "iso3": "NAM",
    "phonecode": "264",
    "capital": "Windhoek",
    "currency": "NAD",
    "native": "Namibia",
    "emoji": "🇳🇦"
  },
  {
    "id": 153,
    "name": "Nauru",
    "iso2": "NR",
    "iso3": "NRU",
    "phonecode": "674",
    "capital": "Yaren",
    "currency": "AUD",
    "native": "Nauru",
    "emoji": "🇳🇷"
  },
  {
    "id": 154,
    "name": "Nepal",
    "iso2": "NP",
    "iso3": "NPL",
    "phonecode": "977",
    "capital": "Kathmandu",
    "currency": "NPR",
    "native": "नपल",
    "emoji": "🇳🇵"
  },
  {
    "id": 155,
    "name": "Bonaire, Sint Eustatius and Saba",
    "iso2": "BQ",
    "iso3": "BES",
    "phonecode": "599",
    "capital": "Kralendijk",
    "currency": "USD",
    "native": "Caribisch Nederland",
    "emoji": "🇧🇶"
  },
  {
    "id": 156,
    "name": "Netherlands",
    "iso2": "NL",
    "iso3": "NLD",
    "phonecode": "31",
    "capital": "Amsterdam",
    "currency": "EUR",
    "native": "Nederland",
    "emoji": "🇳🇱"
  },
  {
    "id": 157,
    "name": "New Caledonia",
    "iso2": "NC",
    "iso3": "NCL",
    "phonecode": "687",
    "capital": "Noumea",
    "currency": "XPF",
    "native": "Nouvelle-Calédonie",
    "emoji": "🇳🇨"
  },
  {
    "id": 158,
    "name": "New Zealand",
    "iso2": "NZ",
    "iso3": "NZL",
    "phonecode": "64",
    "capital": "Wellington",
    "currency": "NZD",
    "native": "New Zealand",
    "emoji": "🇳🇿"
  },
  {
    "id": 159,
    "name": "Nicaragua",
    "iso2": "NI",
    "iso3": "NIC",
    "phonecode": "505",
    "capital": "Managua",
    "currency": "NIO",
    "native": "Nicaragua",
    "emoji": "🇳🇮"
  },
  {
    "id": 160,
    "name": "Niger",
    "iso2": "NE",
    "iso3": "NER",
    "phonecode": "227",
    "capital": "Niamey",
    "currency": "XOF",
    "native": "Niger",
    "emoji": "🇳🇪"
  },
  {
    "id": 161,
    "name": "Nigeria",
    "iso2": "NG",
    "iso3": "NGA",
    "phonecode": "234",
    "capital": "Abuja",
    "currency": "NGN",
    "native": "Nigeria",
    "emoji": "🇳🇬"
  },
  {
    "id": 162,
    "name": "Niue",
    "iso2": "NU",
    "iso3": "NIU",
    "phonecode": "683",
    "capital": "Alofi",
    "currency": "NZD",
    "native": "Niuē",
    "emoji": "🇳🇺"
  },
  {
    "id": 163,
    "name": "Norfolk Island",
    "iso2": "NF",
    "iso3": "NFK",
    "phonecode": "672",
    "capital": "Kingston",
    "currency": "AUD",
    "native": "Norfolk Island",
    "emoji": "🇳🇫"
  },
  {
    "id": 164,
    "name": "Northern Mariana Islands",
    "iso2": "MP",
    "iso3": "MNP",
    "phonecode": "+1-670",
    "capital": "Saipan",
    "currency": "USD",
    "native": "Northern Mariana Islands",
    "emoji": "🇲🇵"
  },
  {
    "id": 165,
    "name": "Norway",
    "iso2": "NO",
    "iso3": "NOR",
    "phonecode": "47",
    "capital": "Oslo",
    "currency": "NOK",
    "native": "Norge",
    "emoji": "🇳🇴"
  },
  {
    "id": 166,
    "name": "Oman",
    "iso2": "OM",
    "iso3": "OMN",
    "phonecode": "968",
    "capital": "Muscat",
    "currency": "OMR",
    "native": "عمان",
    "emoji": "🇴🇲"
  },
  {
    "id": 167,
    "name": "Pakistan",
    "iso2": "PK",
    "iso3": "PAK",
    "phonecode": "92",
    "capital": "Islamabad",
    "currency": "PKR",
    "native": "Pakistan",
    "emoji": "🇵🇰"
  },
  {
    "id": 168,
    "name": "Palau",
    "iso2": "PW",
    "iso3": "PLW",
    "phonecode": "680",
    "capital": "Melekeok",
    "currency": "USD",
    "native": "Palau",
    "emoji": "🇵🇼"
  },
  {
    "id": 169,
    "name": "Palestinian Territory Occupied",
    "iso2": "PS",
    "iso3": "PSE",
    "phonecode": "970",
    "capital": "East Jerusalem",
    "currency": "ILS",
    "native": "فلسطين",
    "emoji": "🇵🇸"
  },
  {
    "id": 170,
    "name": "Panama",
    "iso2": "PA",
    "iso3": "PAN",
    "phonecode": "507",
    "capital": "Panama City",
    "currency": "PAB",
    "native": "Panamá",
    "emoji": "🇵🇦"
  },
  {
    "id": 171,
    "name": "Papua new Guinea",
    "iso2": "PG",
    "iso3": "PNG",
    "phonecode": "675",
    "capital": "Port Moresby",
    "currency": "PGK",
    "native": "Papua Niugini",
    "emoji": "🇵🇬"
  },
  {
    "id": 172,
    "name": "Paraguay",
    "iso2": "PY",
    "iso3": "PRY",
    "phonecode": "595",
    "capital": "Asuncion",
    "currency": "PYG",
    "native": "Paraguay",
    "emoji": "🇵🇾"
  },
  {
    "id": 173,
    "name": "Peru",
    "iso2": "PE",
    "iso3": "PER",
    "phonecode": "51",
    "capital": "Lima",
    "currency": "PEN",
    "native": "Perú",
    "emoji": "🇵🇪"
  },
  {
    "id": 174,
    "name": "Philippines",
    "iso2": "PH",
    "iso3": "PHL",
    "phonecode": "63",
    "capital": "Manila",
    "currency": "PHP",
    "native": "Pilipinas",
    "emoji": "🇵🇭"
  },
  {
    "id": 175,
    "name": "Pitcairn Island",
    "iso2": "PN",
    "iso3": "PCN",
    "phonecode": "870",
    "capital": "Adamstown",
    "currency": "NZD",
    "native": "Pitcairn Islands",
    "emoji": "🇵🇳"
  },
  {
    "id": 176,
    "name": "Poland",
    "iso2": "PL",
    "iso3": "POL",
    "phonecode": "48",
    "capital": "Warsaw",
    "currency": "PLN",
    "native": "Polska",
    "emoji": "🇵🇱"
  },
  {
    "id": 177,
    "name": "Portugal",
    "iso2": "PT",
    "iso3": "PRT",
    "phonecode": "351",
    "capital": "Lisbon",
    "currency": "EUR",
    "native": "Portugal",
    "emoji": "🇵🇹"
  },
  {
    "id": 178,
    "name": "Puerto Rico",
    "iso2": "PR",
    "iso3": "PRI",
    "phonecode": "+1-787 and 1-939",
    "capital": "San Juan",
    "currency": "USD",
    "native": "Puerto Rico",
    "emoji": "🇵🇷"
  },
  {
    "id": 179,
    "name": "Qatar",
    "iso2": "QA",
    "iso3": "QAT",
    "phonecode": "974",
    "capital": "Doha",
    "currency": "QAR",
    "native": "قطر",
    "emoji": "🇶🇦"
  },
  {
    "id": 180,
    "name": "Reunion",
    "iso2": "RE",
    "iso3": "REU",
    "phonecode": "262",
    "capital": "Saint-Denis",
    "currency": "EUR",
    "native": "La Réunion",
    "emoji": "🇷🇪"
  },
  {
    "id": 181,
    "name": "Romania",
    "iso2": "RO",
    "iso3": "ROU",
    "phonecode": "40",
    "capital": "Bucharest",
    "currency": "RON",
    "native": "România",
    "emoji": "🇷🇴"
  },
  {
    "id": 182,
    "name": "Russia",
    "iso2": "RU",
    "iso3": "RUS",
    "phonecode": "7",
    "capital": "Moscow",
    "currency": "RUB",
    "native": "Россия",
    "emoji": "🇷🇺"
  },
  {
    "id": 183,
    "name": "Rwanda",
    "iso2": "RW",
    "iso3": "RWA",
    "phonecode": "250",
    "capital": "Kigali",
    "currency": "RWF",
    "native": "Rwanda",
    "emoji": "🇷🇼"
  },
  {
    "id": 184,
    "name": "Saint Helena",
    "iso2": "SH",
    "iso3": "SHN",
    "phonecode": "290",
    "capital": "Jamestown",
    "currency": "SHP",
    "native": "Saint Helena",
    "emoji": "🇸🇭"
  },
  {
    "id": 185,
    "name": "Saint Kitts And Nevis",
    "iso2": "KN",
    "iso3": "KNA",
    "phonecode": "+1-869",
    "capital": "Basseterre",
    "currency": "XCD",
    "native": "Saint Kitts and Nevis",
    "emoji": "🇰🇳"
  },
  {
    "id": 186,
    "name": "Saint Lucia",
    "iso2": "LC",
    "iso3": "LCA",
    "phonecode": "+1-758",
    "capital": "Castries",
    "currency": "XCD",
    "native": "Saint Lucia",
    "emoji": "🇱🇨"
  },
  {
    "id": 187,
    "name": "Saint Pierre and Miquelon",
    "iso2": "PM",
    "iso3": "SPM",
    "phonecode": "508",
    "capital": "Saint-Pierre",
    "currency": "EUR",
    "native": "Saint-Pierre-et-Miquelon",
    "emoji": "🇵🇲"
  },
  {
    "id": 188,
    "name": "Saint Vincent And The Grenadines",
    "iso2": "VC",
    "iso3": "VCT",
    "phonecode": "+1-784",
    "capital": "Kingstown",
    "currency": "XCD",
    "native": "Saint Vincent and the Grenadines",
    "emoji": "🇻🇨"
  },
  {
    "id": 189,
    "name": "Saint-Barthelemy",
    "iso2": "BL",
    "iso3": "BLM",
    "phonecode": "590",
    "capital": "Gustavia",
    "currency": "EUR",
    "native": "Saint-Barthélemy",
    "emoji": "🇧🇱"
  },
  {
    "id": 190,
    "name": "Saint-Martin (French part)",
    "iso2": "MF",
    "iso3": "MAF",
    "phonecode": "590",
    "capital": "Marigot",
    "currency": "EUR",
    "native": "Saint-Martin",
    "emoji": "🇲🇫"
  },
  {
    "id": 191,
    "name": "Samoa",
    "iso2": "WS",
    "iso3": "WSM",
    "phonecode": "685",
    "capital": "Apia",
    "currency": "WST",
    "native": "Samoa",
    "emoji": "🇼🇸"
  },
  {
    "id": 192,
    "name": "San Marino",
    "iso2": "SM",
    "iso3": "SMR",
    "phonecode": "378",
    "capital": "San Marino",
    "currency": "EUR",
    "native": "San Marino",
    "emoji": "🇸🇲"
  },
  {
    "id": 193,
    "name": "Sao Tome and Principe",
    "iso2": "ST",
    "iso3": "STP",
    "phonecode": "239",
    "capital": "Sao Tome",
    "currency": "STD",
    "native": "São Tomé e Príncipe",
    "emoji": "🇸🇹"
  },
  {
    "id": 194,
    "name": "Saudi Arabia",
    "iso2": "SA",
    "iso3": "SAU",
    "phonecode": "966",
    "capital": "Riyadh",
    "currency": "SAR",
    "native": "المملكة العربية السعودية",
    "emoji": "🇸🇦"
  },
  {
    "id": 195,
    "name": "Senegal",
    "iso2": "SN",
    "iso3": "SEN",
    "phonecode": "221",
    "capital": "Dakar",
    "currency": "XOF",
    "native": "Sénégal",
    "emoji": "🇸🇳"
  },
  {
    "id": 196,
    "name": "Serbia",
    "iso2": "RS",
    "iso3": "SRB",
    "phonecode": "381",
    "capital": "Belgrade",
    "currency": "RSD",
    "native": "Србија",
    "emoji": "🇷🇸"
  },
  {
    "id": 197,
    "name": "Seychelles",
    "iso2": "SC",
    "iso3": "SYC",
    "phonecode": "248",
    "capital": "Victoria",
    "currency": "SCR",
    "native": "Seychelles",
    "emoji": "🇸🇨"
  },
  {
    "id": 198,
    "name": "Sierra Leone",
    "iso2": "SL",
    "iso3": "SLE",
    "phonecode": "232",
    "capital": "Freetown",
    "currency": "SLL",
    "native": "Sierra Leone",
    "emoji": "🇸🇱"
  },
  {
    "id": 199,
    "name": "Singapore",
    "iso2": "SG",
    "iso3": "SGP",
    "phonecode": "65",
    "capital": "Singapur",
    "currency": "SGD",
    "native": "Singapore",
    "emoji": "🇸🇬"
  },
  {
    "id": 200,
    "name": "Slovakia",
    "iso2": "SK",
    "iso3": "SVK",
    "phonecode": "421",
    "capital": "Bratislava",
    "currency": "EUR",
    "native": "Slovensko",
    "emoji": "🇸🇰"
  },
  {
    "id": 201,
    "name": "Slovenia",
    "iso2": "SI",
    "iso3": "SVN",
    "phonecode": "386",
    "capital": "Ljubljana",
    "currency": "EUR",
    "native": "Slovenija",
    "emoji": "🇸🇮"
  },
  {
    "id": 202,
    "name": "Solomon Islands",
    "iso2": "SB",
    "iso3": "SLB",
    "phonecode": "677",
    "capital": "Honiara",
    "currency": "SBD",
    "native": "Solomon Islands",
    "emoji": "🇸🇧"
  },
  {
    "id": 203,
    "name": "Somalia",
    "iso2": "SO",
    "iso3": "SOM",
    "phonecode": "252",
    "capital": "Mogadishu",
    "currency": "SOS",
    "native": "Soomaaliya",
    "emoji": "🇸🇴"
  },
  {
    "id": 204,
    "name": "South Africa",
    "iso2": "ZA",
    "iso3": "ZAF",
    "phonecode": "27",
    "capital": "Pretoria",
    "currency": "ZAR",
    "native": "South Africa",
    "emoji": "🇿🇦"
  },
  {
    "id": 205,
    "name": "South Georgia",
    "iso2": "GS",
    "iso3": "SGS",
    "phonecode": "500",
    "capital": "Grytviken",
    "currency": "GBP",
    "native": "South Georgia",
    "emoji": "🇬🇸"
  },
  {
    "id": 206,
    "name": "South Sudan",
    "iso2": "SS",
    "iso3": "SSD",
    "phonecode": "211",
    "capital": "Juba",
    "currency": "SSP",
    "native": "South Sudan",
    "emoji": "🇸🇸"
  },
  {
    "id": 207,
    "name": "Spain",
    "iso2": "ES",
    "iso3": "ESP",
    "phonecode": "34",
    "capital": "Madrid",
    "currency": "EUR",
    "native": "España",
    "emoji": "🇪🇸"
  },
  {
    "id": 208,
    "name": "Sri Lanka",
    "iso2": "LK",
    "iso3": "LKA",
    "phonecode": "94",
    "capital": "Colombo",
    "currency": "LKR",
    "native": "śrī laṃkāva",
    "emoji": "🇱🇰"
  },
  {
    "id": 209,
    "name": "Sudan",
    "iso2": "SD",
    "iso3": "SDN",
    "phonecode": "249",
    "capital": "Khartoum",
    "currency": "SDG",
    "native": "السودان",
    "emoji": "🇸🇩"
  },
  {
    "id": 210,
    "name": "Suriname",
    "iso2": "SR",
    "iso3": "SUR",
    "phonecode": "597",
    "capital": "Paramaribo",
    "currency": "SRD",
    "native": "Suriname",
    "emoji": "🇸🇷"
  },
  {
    "id": 211,
    "name": "Svalbard And Jan Mayen Islands",
    "iso2": "SJ",
    "iso3": "SJM",
    "phonecode": "47",
    "capital": "Longyearbyen",
    "currency": "NOK",
    "native": "Svalbard og Jan Mayen",
    "emoji": "🇸🇯"
  },
  {
    "id": 212,
    "name": "Swaziland",
    "iso2": "SZ",
    "iso3": "SWZ",
    "phonecode": "268",
    "capital": "Mbabane",
    "currency": "SZL",
    "native": "Swaziland",
    "emoji": "🇸🇿"
  },
  {
    "id": 213,
    "name": "Sweden",
    "iso2": "SE",
    "iso3": "SWE",
    "phonecode": "46",
    "capital": "Stockholm",
    "currency": "SEK",
    "native": "Sverige",
    "emoji": "🇸🇪"
  },
  {
    "id": 214,
    "name": "Switzerland",
    "iso2": "CH",
    "iso3": "CHE",
    "phonecode": "41",
    "capital": "Bern",
    "currency": "CHF",
    "native": "Schweiz",
    "emoji": "🇨🇭"
  },
  {
    "id": 215,
    "name": "Syria",
    "iso2": "SY",
    "iso3": "SYR",
    "phonecode": "963",
    "capital": "Damascus",
    "currency": "SYP",
    "native": "سوريا",
    "emoji": "🇸🇾"
  },
  {
    "id": 216,
    "name": "Taiwan",
    "iso2": "TW",
    "iso3": "TWN",
    "phonecode": "886",
    "capital": "Taipei",
    "currency": "TWD",
    "native": "臺灣",
    "emoji": "🇹🇼"
  },
  {
    "id": 217,
    "name": "Tajikistan",
    "iso2": "TJ",
    "iso3": "TJK",
    "phonecode": "992",
    "capital": "Dushanbe",
    "currency": "TJS",
    "native": "Тоҷикистон",
    "emoji": "🇹🇯"
  },
  {
    "id": 218,
    "name": "Tanzania",
    "iso2": "TZ",
    "iso3": "TZA",
    "phonecode": "255",
    "capital": "Dodoma",
    "currency": "TZS",
    "native": "Tanzania",
    "emoji": "🇹🇿"
  },
  {
    "id": 219,
    "name": "Thailand",
    "iso2": "TH",
    "iso3": "THA",
    "phonecode": "66",
    "capital": "Bangkok",
    "currency": "THB",
    "native": "ประเทศไทย",
    "emoji": "🇹🇭"
  },
  {
    "id": 220,
    "name": "Togo",
    "iso2": "TG",
    "iso3": "TGO",
    "phonecode": "228",
    "capital": "Lome",
    "currency": "XOF",
    "native": "Togo",
    "emoji": "🇹🇬"
  },
  {
    "id": 221,
    "name": "Tokelau",
    "iso2": "TK",
    "iso3": "TKL",
    "phonecode": "690",
    "capital": "",
    "currency": "NZD",
    "native": "Tokelau",
    "emoji": "🇹🇰"
  },
  {
    "id": 222,
    "name": "Tonga",
    "iso2": "TO",
    "iso3": "TON",
    "phonecode": "676",
    "capital": "Nuku'alofa",
    "currency": "TOP",
    "native": "Tonga",
    "emoji": "🇹🇴"
  },
  {
    "id": 223,
    "name": "Trinidad And Tobago",
    "iso2": "TT",
    "iso3": "TTO",
    "phonecode": "+1-868",
    "capital": "Port of Spain",
    "currency": "TTD",
    "native": "Trinidad and Tobago",
    "emoji": "🇹🇹"
  },
  {
    "id": 224,
    "name": "Tunisia",
    "iso2": "TN",
    "iso3": "TUN",
    "phonecode": "216",
    "capital": "Tunis",
    "currency": "TND",
    "native": "تونس",
    "emoji": "🇹🇳"
  },
  {
    "id": 225,
    "name": "Turkey",
    "iso2": "TR",
    "iso3": "TUR",
    "phonecode": "90",
    "capital": "Ankara",
    "currency": "TRY",
    "native": "Türkiye",
    "emoji": "🇹🇷"
  },
  {
    "id": 226,
    "name": "Turkmenistan",
    "iso2": "TM",
    "iso3": "TKM",
    "phonecode": "993",
    "capital": "Ashgabat",
    "currency": "TMT",
    "native": "Türkmenistan",
    "emoji": "🇹🇲"
  },
  {
    "id": 227,
    "name": "Turks And Caicos Islands",
    "iso2": "TC",
    "iso3": "TCA",
    "phonecode": "+1-649",
    "capital": "Cockburn Town",
    "currency": "USD",
    "native": "Turks and Caicos Islands",
    "emoji": "🇹🇨"
  },
  {
    "id": 228,
    "name": "Tuvalu",
    "iso2": "TV",
    "iso3": "TUV",
    "phonecode": "688",
    "capital": "Funafuti",
    "currency": "AUD",
    "native": "Tuvalu",
    "emoji": "🇹🇻"
  },
  {
    "id": 229,
    "name": "Uganda",
    "iso2": "UG",
    "iso3": "UGA",
    "phonecode": "256",
    "capital": "Kampala",
    "currency": "UGX",
    "native": "Uganda",
    "emoji": "🇺🇬"
  },
  {
    "id": 230,
    "name": "Ukraine",
    "iso2": "UA",
    "iso3": "UKR",
    "phonecode": "380",
    "capital": "Kyiv",
    "currency": "UAH",
    "native": "Україна",
    "emoji": "🇺🇦"
  },
  {
    "id": 231,
    "name": "United Arab Emirates",
    "iso2": "AE",
    "iso3": "ARE",
    "phonecode": "971",
    "capital": "Abu Dhabi",
    "currency": "AED",
    "native": "دولة الإمارات العربية المتحدة",
    "emoji": "🇦🇪"
  },
  {
    "id": 232,
    "name": "United Kingdom",
    "iso2": "GB",
    "iso3": "GBR",
    "phonecode": "44",
    "capital": "London",
    "currency": "GBP",
    "native": "United Kingdom",
    "emoji": "🇬🇧"
  },
  {
    "id": 233,
    "name": "United States",
    "iso2": "US",
    "iso3": "USA",
    "phonecode": "1",
    "capital": "Washington",
    "currency": "USD",
    "native": "United States",
    "emoji": "🇺🇸"
  },
  {
    "id": 234,
    "name": "United States Minor Outlying Islands",
    "iso2": "UM",
    "iso3": "UMI",
    "phonecode": "1",
    "capital": "",
    "currency": "USD",
    "native": "United States Minor Outlying Islands",
    "emoji": "🇺🇲"
  },
  {
    "id": 235,
    "name": "Uruguay",
    "iso2": "UY",
    "iso3": "URY",
    "phonecode": "598",
    "capital": "Montevideo",
    "currency": "UYU",
    "native": "Uruguay",
    "emoji": "🇺🇾"
  },
  {
    "id": 236,
    "name": "Uzbekistan",
    "iso2": "UZ",
    "iso3": "UZB",
    "phonecode": "998",
    "capital": "Tashkent",
    "currency": "UZS",
    "native": "O‘zbekiston",
    "emoji": "🇺🇿"
  },
  {
    "id": 237,
    "name": "Vanuatu",
    "iso2": "VU",
    "iso3": "VUT",
    "phonecode": "678",
    "capital": "Port Vila",
    "currency": "VUV",
    "native": "Vanuatu",
    "emoji": "🇻🇺"
  },
  {
    "id": 238,
    "name": "Vatican City State (Holy See)",
    "iso2": "VA",
    "iso3": "VAT",
    "phonecode": "379",
    "capital": "Vatican City",
    "currency": "EUR",
    "native": "Vaticano",
    "emoji": "🇻🇦"
  },
  {
    "id": 239,
    "name": "Venezuela",
    "iso2": "VE",
    "iso3": "VEN",
    "phonecode": "58",
    "capital": "Caracas",
    "currency": "VES",
    "native": "Venezuela",
    "emoji": "🇻🇪"
  },
  {
    "id": 240,
    "name": "Vietnam",
    "iso2": "VN",
    "iso3": "VNM",
    "phonecode": "84",
    "capital": "Hanoi",
    "currency": "VND",
    "native": "Việt Nam",
    "emoji": "🇻🇳"
  },
  {
    "id": 241,
    "name": "Virgin Islands (British)",
    "iso2": "VG",
    "iso3": "VGB",
    "phonecode": "+1-284",
    "capital": "Road Town",
    "currency": "USD",
    "native": "British Virgin Islands",
    "emoji": "🇻🇬"
  },
  {
    "id": 242,
    "name": "Virgin Islands (US)",
    "iso2": "VI",
    "iso3": "VIR",
    "phonecode": "+1-340",
    "capital": "Charlotte Amalie",
    "currency": "USD",
    "native": "United States Virgin Islands",
    "emoji": "🇻🇮"
  },
  {
    "id": 243,
    "name": "Wallis And Futuna Islands",
    "iso2": "WF",
    "iso3": "WLF",
    "phonecode": "681",
    "capital": "Mata Utu",
    "currency": "XPF",
    "native": "Wallis et Futuna",
    "emoji": "🇼🇫"
  },
  {
    "id": 244,
    "name": "Western Sahara",
    "iso2": "EH",
    "iso3": "ESH",
    "phonecode": "212",
    "capital": "El-Aaiun",
    "currency": "MAD",
    "native": "الصحراء الغربية",
    "emoji": "🇪🇭"
  },
  {
    "id": 245,
    "name": "Yemen",
    "iso2": "YE",
    "iso3": "YEM",
    "phonecode": "967",
    "capital": "Sanaa",
    "currency": "YER",
    "native": "اليَمَن",
    "emoji": "🇾🇪"
  },
  {
    "id": 246,
    "name": "Zambia",
    "iso2": "ZM",
    "iso3": "ZMB",
    "phonecode": "260",
    "capital": "Lusaka",
    "currency": "ZMW",
    "native": "Zambia",
    "emoji": "🇿🇲"
  },
  {
    "id": 247,
    "name": "Zimbabwe",
    "iso2": "ZW",
    "iso3": "ZWE",
    "phonecode": "263",
    "capital": "Harare",
    "currency": "ZWL",
    "native": "Zimbabwe",
    "emoji": "🇿🇼"
  },
  {
    "id": 248,
    "name": "Kosovo",
    "iso2": "XK",
    "iso3": "XKX",
    "phonecode": "383",
    "capital": "Pristina",
    "currency": "EUR",
    "native": "Republika e Kosovës",
    "emoji": "🇽🇰"
  },
  {
    "id": 249,
    "name": "Curaçao",
    "iso2": "CW",
    "iso3": "CUW",
    "phonecode": "599",
    "capital": "Willemstad",
    "currency": "ANG",
    "native": "Curaçao",
    "emoji": "🇨🇼"
  },
  {
    "id": 250,
    "name": "Sint Maarten (Dutch part)",
    "iso2": "SX",
    "iso3": "SXM",
    "phonecode": "1721",
    "capital": "Philipsburg",
    "currency": "ANG",
    "native": "Sint Maarten",
    "emoji": "🇸🇽"
  }
]